server:
  port: 8761
eureka:
  client:
    registerWithEureka: false  # 是否将自己注册到Eureka Server.默认为true，由于当前应用是Eureka Server，故设置为false
    fetchRegistry: false  # 是否从Eureka Server获取注册信息, 因为这里是一个单点的Eureka Server，不需要同步其他的Server节点的数据，故设置为false
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka/  # 设置带用户名密码的访问形式
#      defaultZone: http://localhost:8761/eureka/  # 设置带用户名密码的访问形式

security:
  basic:
    enabled: true    # 开启基于HTTP basic的认证
  user:
    name: user
    password: password123
